feat: 기본 틀 나누기
Soongsil-Developers/ssu-tracker pull request #6
Opened 2022-09-12 16:10 UTC by nijuy

### 반영 브랜치

feature/frame -> main 

### 변경 사항

기본 틀 구성을 위한 컴포넌트를 추가했으며, 일부 컴포넌트의 경우 기본적인 내용을 삽입했습니다.
~~그냥 뭐뭐뭐 자리 이렇게만 적어놓기가 민망해서요~~

### 테스트 결과

나중에 추가하겠스빈다

### Issue

resolved: #

2022-09-12 16:27 UTC, nijuy commented on src/App.tsx
> +      <Route index element={<Main />} />
작업할 때 편할 거 같아서 실행했을 때 바로 Main 컴포넌트 보여주도록 넣어놨습니다..!!

2022-09-12 16:27 UTC, nijuy commented on src/pages/main/Profile.tsx
> +      <div>프로필</div>
추후에 사용자 프로필 이미지 / 이름 / 학과 부분이 들어갈 영역입니다

2022-09-12 16:30 UTC, nijuy commented on src/pages/main/Streak.tsx
> +      )}
option 변수는 드롭박스 내 선택된 옵션을 의미하는 변수입니다! 
지금 Typography 들어간 자리에 라이브러리 불러와서 넣으면 될 거 같아욥

2022-09-13 00:48 UTC, blan19 requested changes
pages는 말 그대로 페이지들만을 위한 폴더입니다! 
Main 페이지의 하위 컴포넌트들은 components/[domain]/* 이렇게 넣어두시면 될 것 같아요! 

너무 고생하셨습니다 ㅎ-ㅎbb

2022-09-13 00:48 UTC, blan19 commented on src/pages/main/Streak.tsx
> +  };
지금 체인지옵션에서 탭바의 벨류가 바뀔때마다 Main 페이지에 있는 profile, streak, card 전체가 리렌더링 될 것 같은데 이부분에서 잔디밭과 그래프, 탭바만 리렌더링되도록 최적화를 고려해야될것같아요!

2022-09-13 00:48 UTC, blan19 commented on src/pages/main/Streak.tsx
> +      )}
bb

2022-09-13 00:54 UTC, nijuy commented on package.json
> +    "antd": "^4.23.1",
엇 지금은 안 쓰고 있는데 반응형(?) 작업하려면 antd에 있는 row랑 col 써야할 거 같아서 설치했었어요!

2022-09-13 00:55 UTC, nijuy commented on src/pages/main/Streak.tsx
> +  };
안그래도 그 부분 신경 써야겠다고 생각했는데 짚어주셔서 감사합니도 (〃⌒∇⌒〃)ゝ

2022-09-13 00:56 UTC, nijuy commented
> pages는 말 그대로 페이지들만을 위한 폴더입니다! 
> 
> Main 페이지의 하위 컴포넌트들은 components/[domain]/* 이렇게 넣어두시면 될 것 같아요! 
> 
> 
> 
> 너무 고생하셨습니다 ㅎ-ㅎbb

아하 제가 이해를 잘못 하고 있었네요~~! 수업 끝나자마저 이거부터 수정하겠습니당덩 😉

2022-09-13 01:22 UTC, nijuy commented on package.json
> +    "antd": "^4.23.1",
🤔...!! 카드나 그런거 만들때도 쓸 수는 있을 거 같은데 그정돈 스타일 컴포넌트로 만들어두고 써도 될 거 같아요!!

2022-09-13 08:11 UTC, leehyewon0531 approved these changes
넘 잘해주신 것 같아요 ㅠㅠㅠㅠ!!! 고생하셨습니다!!! 최고 👍

2022-09-13 08:14 UTC, nijuy commented on src/components/typography.tsx
> +    line-height: 2.25rem;
> 유진님!! 이건 그냥 제가 몰라서... 물어보는 건데 Typography 컴포넌트는 정확히 어떤 역할을 해주는 컴포넌트인가요?.?

어머나,,, 옆에 깃허브 켜두고 수정 중이었는데 댓글 나타나서 감작 놀랐어요 
Typography 컴포넌트는 준서님께서 미리 만들어두셨던 컴포넌트인데 여기서 무슨 역할을 하는건 아니고 한번 갖다 써봤습니다 ㅎ.ㅎ 스타일이 이미 지정되어 있어서 따로 스타일 적용을 안해줘도 돼요!!

![image](https://user-images.githubusercontent.com/87255462/189848128-424b625e-1cc5-4f01-b25e-15d92affc954.png)

typography.tsx 참고하시면 무슨 스타일 적용되어있는지 보실 수 있어요!!! 👀

2022-09-13 08:31 UTC, leehyewon0531 commented on src/components/typography.tsx
> +    line-height: 2.25rem;
아하 이게 그거였군요,,,!? 감사합니다 ^_^!!!!!!

2022-09-13 08:32 UTC, leehyewon0531 approved these changes

2022-09-13 08:37 UTC, blan19 approved these changes
고생하셨습니다 👍👍

2022-09-13 08:37 UTC, blan19 commented on src/components/typography.tsx
> +    line-height: 2.25rem;
저걸로 저희가 피그마에서 사용하는 폰트 사이즈나 폰트 크기 등을 미리 선언해서 이후 글이 필요한 곳에 쓰면 됩니다 as 프롭스로 원하는 태그 지정해서 만들어 쓰면돼요! as="h1", as="span" 등등 

`<Typography>
    그냥 텍스트
    <HighLight>색이 다른 강조할 부분</HighLight>
    ....
</Typography>`

이런식으로 써도 되구요!

2022-09-13 08:37 UTC, merged